import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster"

import Header from '@/components/Header'
import { ClerkProvider} from "@clerk/nextjs";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NoteSelfy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
            <Header />
              {children}
            <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
 
         
       
            

