import { Inter, Playfair_Display } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster"
import { twMerge } from "tailwind-merge"

import Header from '@/components/Header'
import { ClerkProvider} from "@clerk/nextjs";


const inter = Inter({ subsets: ["latin"], variable: '--font-sans' });
const playfair = Playfair_Display({ subsets: ["latin"], variable: '--font-serif' });

export const metadata = {
  title: "NoteSelfy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
    <ClerkProvider>
      <html lang="en">
        <body 
        className={twMerge(
          inter.variable, 
          playfair.variable, 
          "bg-gray-900 text-orange-50 font-sans"
          )}
          >
            <Header />
              {children}
            <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
 
         
       
            

